#
# JUPITER
#
# apache + php + mysql
#

version: '3'

services:
  web:
    image: ../../db.apache-php
    ports:
      - "80:80"
    volumes:
      - ${APP_ROOT}/www:/var/www
      - ${APP_ROOT}/data/storage:/var/www/storage
      - ${APP_ROOT}/logs/apache:????
      - ${APP_ROOT}/logs/php:????
  db:
    image: ../../db.mysql
    ports:
          - "3306:3306"
    volumes:
      - ${APP_ROOT}/data/database:????
      - ${APP_ROOT}/logs/database:????
