#
# SOL
#
# nginx + mysql
#

version: '3.7'

services:
  web:
    context: ${SW_APACHE_PHP}
    dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - __APP_ROOT__/www:/var/www
      - __APP_ROOT__/configs/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    context: ${DB_MYSQL}
    dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    volumes:
      - __APP_ROOT__/data/database:????
      - __APP_ROOT__/logs/database:????
